-- Criação das tabelas
CREATE TABLE TB_MOTTU_IOT(
  iot_hash  NUMBER  (5)     NOT NULL,
  latitude  NUMBER  (7, 5)  NOT NULL,
  longitude NUMBER  (8, 5)  NOT NULL
);

CREATE TABLE TB_MOTTU_MODELO(
  id_modelo   NUMBER    (5)   NOT NULL,
  nm_modelo   VARCHAR2  (20)  NOT NULL,
  desc_modelo VARCHAR2  (255) NULL
);

CREATE TABLE TB_MOTTU_MOTO(
  id_moto   NUMBER    (5)   NOT NULL,
  iot_hash  NUMBER    (5)   NOT NULL,
  id_stat   NUMBER    (2)   NOT NULL,
  id_filial NUMBER    (5)   NOT NULL,
  id_modelo NUMBER    (5)   NOT NULL,
  placa     VARCHAR2  (15)  NOT NULL,
  nr_motor  VARCHAR2  (100) NOT NULL
);

CREATE TABLE TB_MOTTU_STATUS(
  id_stat NUMBER    (2)   NOT NULL,
  nm_stat VARCHAR2  (25)  NOT NULL
);

CREATE TABLE TB_MOTTU_AREA(
  id_area   NUMBER  (5) NOT NULL,
  id_filial NUMBER  (5) NOT NULL,
  id_stat   NUMBER  (2) NOT NULL,
  pos_x     NUMBER  (4) NOT NULL,
  pos_y     NUMBER  (4) NOT NULL
);

CREATE TABLE TB_MOTTU_FILIAL(
  id_filial   NUMBER    (5)   NOT NULL,
  id_endereco NUMBER    (5)   NOT NULL,
  nm_filial   VARCHAR2  (50)  NOT NULL
);

CREATE TABLE TB_MOTTU_ENDERECO(
  id_endereco NUMBER    (5)   NOT NULL,
  id_bairro   NUMBER    (5)   NOT NULL,
  logradouro  VARCHAR2  (150) NOT NULL,
  nr_endereco NUMBER    (5)   NOT NULL,
  nr_cep      CHAR      (8)   NOT NULL,
  complemento VARCHAR2  (50)  NULL
);

CREATE TABLE TB_MOTTU_BAIRRO(
  id_bairro   NUMBER    (5)   NOT NULL,
  id_cidade   NUMBER    (5)   NOT NULL,
  nm_bairro   VARCHAR2  (50)  NOT NULL
);

CREATE TABLE TB_MOTTU_CIDADE(
  id_cidade   NUMBER    (5)   NOT NULL,
  id_estado   NUMBER    (5)   NOT NULL,
  nm_cidade   VARCHAR2  (50)  NOT NULL
);

CREATE TABLE TB_MOTTU_ESTADO(
  id_estado    NUMBER    (5)   NOT NULL,
  id_pais      NUMBER    (5)   NOT NULL,
  nm_estado    VARCHAR2  (50)  NOT NULL,
  sigla_estado CHAR      (2)   NOT NULL
);

CREATE TABLE TB_MOTTU_PAIS(
  id_pais   NUMBER    (5)   NOT NULL,
  nm_pais   VARCHAR2  (50)  NOT NULL
);

-- Adicionando as constraints de chave primária e estrangeira
ALTER TABLE TB_MOTTU_IOT
  ADD CONSTRAINT PK_MOTTU_IOT PRIMARY KEY (iot_hash);

ALTER TABLE TB_MOTTU_MODELO
  ADD CONSTRAINT PK_MOTTU_MODELO PRIMARY KEY (id_modelo);

ALTER TABLE TB_MOTTU_MOTO
  ADD CONSTRAINT PK_MOTTU_MOTO PRIMARY KEY (id_moto);

ALTER TABLE TB_MOTTU_STATUS
  ADD CONSTRAINT PK_MOTTU_STATUS PRIMARY KEY (id_stat);

ALTER TABLE TB_MOTTU_AREA
  ADD CONSTRAINT PK_MOTTU_AREA PRIMARY KEY (id_area);

ALTER TABLE TB_MOTTU_FILIAL
  ADD CONSTRAINT PK_MOTTU_FILIAL PRIMARY KEY (id_filial);

ALTER TABLE TB_MOTTU_ENDERECO
  ADD CONSTRAINT PK_MOTTU_ENDERECO PRIMARY KEY (id_endereco);

ALTER TABLE TB_MOTTU_BAIRRO
  ADD CONSTRAINT PK_MOTTU_BAIRRO PRIMARY KEY (id_bairro);

ALTER TABLE TB_MOTTU_CIDADE
  ADD CONSTRAINT PK_MOTTU_CIDADE PRIMARY KEY (id_cidade);

ALTER TABLE TB_MOTTU_ESTADO
  ADD CONSTRAINT PK_MOTTU_ESTADO PRIMARY KEY (id_estado);

ALTER TABLE TB_MOTTU_PAIS
  ADD CONSTRAINT PK_MOTTU_PAIS PRIMARY KEY (id_pais);

ALTER TABLE TB_MOTTU_MOTO
  ADD CONSTRAINT FK_MOTTU_MOTO_IOT FOREIGN KEY (iot_hash) REFERENCES TB_MOTTU_IOT (iot_hash);

ALTER TABLE TB_MOTTU_MOTO
  ADD CONSTRAINT FK_MOTTU_MOTO_STATUS FOREIGN KEY (id_stat) REFERENCES TB_MOTTU_STATUS (id_stat);

ALTER TABLE TB_MOTTU_MOTO
  ADD CONSTRAINT FK_MOTTU_MOTO_FILIAL FOREIGN KEY (id_filial) REFERENCES TB_MOTTU_FILIAL (id_filial);

ALTER TABLE TB_MOTTU_MOTO
  ADD CONSTRAINT FK_MOTTU_MOTO_MODELO FOREIGN KEY (id_modelo) REFERENCES TB_MOTTU_MODELO (id_modelo);

ALTER TABLE TB_MOTTU_AREA
  ADD CONSTRAINT FK_MOTTU_AREA_FILIAL FOREIGN KEY (id_filial) REFERENCES TB_MOTTU_FILIAL (id_filial);

ALTER TABLE TB_MOTTU_AREA
  ADD CONSTRAINT FK_MOTTU_AREA_STATUS FOREIGN KEY (id_stat) REFERENCES TB_MOTTU_STATUS (id_stat);

ALTER TABLE TB_MOTTU_FILIAL
  ADD CONSTRAINT FK_MOTTU_FILIAL_ENDERECO FOREIGN KEY (id_endereco) REFERENCES TB_MOTTU_ENDERECO (id_endereco);

ALTER TABLE TB_MOTTU_ENDERECO
  ADD CONSTRAINT FK_MOTTU_ENDERECO_BAIRRO FOREIGN KEY (id_bairro) REFERENCES TB_MOTTU_BAIRRO (id_bairro);

ALTER TABLE TB_MOTTU_BAIRRO
  ADD CONSTRAINT FK_MOTTU_BAIRRO_CIDADE FOREIGN KEY (id_cidade) REFERENCES TB_MOTTU_CIDADE (id_cidade);

ALTER TABLE TB_MOTTU_CIDADE
  ADD CONSTRAINT FK_MOTTU_CIDADE_ESTADO FOREIGN KEY (id_estado) REFERENCES TB_MOTTU_ESTADO (id_estado);

ALTER TABLE TB_MOTTU_ESTADO
  ADD CONSTRAINT FK_MOTTU_ESTADO_PAIS FOREIGN KEY (id_pais) REFERENCES TB_MOTTU_PAIS (id_pais);

-- Adicionando as constraints de unicidade
ALTER TABLE TB_MOTTU_MOTO
  ADD CONSTRAINT UN_MOTO_PLACA UNIQUE (placa);

ALTER TABLE TB_MOTTU_MOTO
  ADD CONSTRAINT UN_MOTO_NR_MOTOR UNIQUE (nr_motor);

-- Adicionando os índices
CREATE INDEX IDX_MOTTU_MOTO_IOT ON TB_MOTTU_MOTO (iot_hash);

CREATE INDEX IDX_MOTTU_FILIAL_ENDERECO ON TB_MOTTU_FILIAL (id_endereco);